posts/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path('', IndexView.as_view(), name="index"),
    path('detail/<int:pk>/<slug:slug>', PostDetail.as_view(), name="detail"),
    path('category/<int:pk>/<slug:slug>', CategoryDetail.as_view(), name="category_detail"),
    path('tag/<slug:slug>', TagDetail.as_view(), name="tag_detail"),
    path('create-post', CreatePostView.as_view(), name="create_post"),
    path('update-post/<int:pk>/<slug:slug>', UpdatePostView.as_view(), name="update_post"),
    path('delete-post/<int:pk>/<slug:slug>', DeletePostView.as_view(), name="delete_post"),
    path('search/', search, name="search"),
    path('newsletter/', HomeView.as_view(), name="newsletter"),
    # All posts page
    path('blog/', blog, name='post-list'),
]

users/urls.py
from django.urls import path
from . views import *
from django.contrib.auth import views as authViews

app_name = 'users'
urlpatterns = [
    path('', UserListView.as_view(), name='user_list'),
    path('register/', RegisterView.as_view(), name='register'),
    path('login/', UserLoginView.as_view(), name='login'),
    path('logout/', UserLogoutView.as_view(), name='logout'),
    path('password-change/', authViews.PasswordChangeView.as_view(), name='password_change'),
    path('password-change-done/', authViews.PasswordChangeDoneView.as_view(), name='password_change_done'),
    path('update-profile/<slug:slug>/', UserProfileUpdateView.as_view(), name='update_profile'),
    path('myprofile/', UserProfileView.as_view(), name='myprofile'),
    path('<int:pk>/', UserPostView.as_view(), name='user_posts'),

]

whiskeyChristmas/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from posts.views import blog


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('posts.urls')),
    path('users/', include('users.urls')),
    path('tinymce/', include('tinymce.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
{% load static %}
{% load custom_tags %}

<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>Whiskey Christmas</title>
  <meta name="description" content="">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="robots" content="all,follow">
  <!-- Fonts -->
  <link href="https://fonts.googleapis.com/css2?family=Mountains+of+Christmas&display=swap" rel="stylesheet">
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,700">
  <!-- end fonts -->
  <link rel="stylesheet" href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}">
  <link rel="stylesheet" href="{% static 'vendor/font-awesome/css/font-awesome.min.css' %}">
  <link rel="stylesheet" href="{% static 'css/fontastic.css' %}">
  <link rel="stylesheet" href="{% static 'vendor/@fancyapps/fancybox/jquery.fancybox.min.css' %}">
  <link rel="stylesheet" href="{% static 'css/style.default.css' %}" id='theme-stylesheet'>
  <link rel="stylesheet" href="{% static 'css/custom.css' %}">
  <link rel="shortcut icon" href="{% static 'img/favicon.png' %}">

  <!-- Tweaks for older IEs--><!--[if lt IE 9]>
  <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
  <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script><![endif]-->
</head>


<!-- banner Section contains site logo and backgorund pic-->
<section style="background: url({% static 'img/banner_bg.png' %}); background-size: cover; background-position: center center" class="hero">
  <div class="container">
    <div class="text-center">
      <h1 style="font-family:Mountains of Christmas" class="display-3">WHISKEY<img src="{% static 'img/whiskeyChristmasLogo_full.gif' %}" alt="logo" style="width:auto;height:75px;">CHRISTMAS</h1>
    </div>
  </div>
</section>

<!-- Main Navbar-->
<nav class="navbar navbar-expand-lg">
  <div class="search-area">
    <div class="search-area-inner d-flex align-items-center justify-content-center">
      <div class="close-btn"><i class="icon-close"></i></div>
      <div class="row d-flex justify-content-center">
        <div class="col-md-8">
          <form action="{% url 'search' %}" method="get" class="search-form">
            <div class="form-group">
              <input type="text" name="q" placeholder="What are you looking for?">
              <button type="submit" class="submit">
                <span style="color: ForestGreen;">
                  <i class="fa fa-search fa-lg"></i>
                </span>
              </button>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
  <div class="container">
    <div class="navbar-header d-flex align-items-center justify-content-between">
      <!-- Toggle Button-->
      <button type="button" data-toggle="collapse" data-target="#navbarcollapse" aria-controls="navbarcollapse" aria-expanded="false" aria-label="Toggle navigation" class="navbar-toggler"><span></span><span></span><span></span></button>
    </div>
    <!-- Navbar Menu -->
    <div id="navbarcollapse" class="collapse navbar-collapse">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item"><a href="{% url 'index' %}" class="nav-link ">Home</a>
        </li>
        <!-- Categories dropdown -->
        <li class="nav-item submenu dropdown">
          <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
            Categories</a>
            <ul class="dropdown-menu">
              {% categories as categories %}
              {% for category in categories %}
              <li class="nav-item submenu dropdown">
                <li class="dropdown-item"><a href="{% url 'category_detail' pk=category.id slug=category.slug %}">{{ category.title }}</a>
                </li>
              </li>
              {% endfor %}
            </ul>
          </li>
          <!-- Members area -->
          <li class="nav-item submenu dropdown">
            <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
              Members Area</a>
              <ul class="dropdown-menu">
                <li class="nav-item submenu dropdown">
                  <li class="dropdown-item"><a href="{% url 'post-list' %}"><i class="fa fa-comments"></i> All Posts</a>
                  </li>
                  <li class="dropdown-item"><a href="{% url 'users:user_list' %}"><i class="fa fa-users"></i> Profiles</a>
                  </li>
                </li>
              </ul>
            </li>
          </ul>

          <!-- authentication links and search-->
          <ul class="nav navbar-nav navbar-right ml-auto">
            {% if user.is_authenticated %}
            <li class="nav-item submenu dropdown">
              <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                USER: {{ user.username }}</a>
                <ul class="dropdown-menu">
                  <li class="dropdown-item"><a href="{% url 'create_post' %}"><i class="fa fa-plus"></i> Post</a></li>
                  <li class="dropdown-item"><a href="{% url 'users:myprofile' %}"><i class="fa fa-user"></i> Profile</a></li>
                  <li class="dropdown-item"><a href="{% url 'users:password_change' %}"><i class="fa fa-unlock"></i> Change Password</a></li>
                  <!-- id url is from another app. use this syntax 'app_name:url_name' -->
                  <li class="dropdown-item"><a href="{% url 'users:logout' %}">
                    <i class="fa fa-sign-out"></i> Logout</a></li>
                  </ul>
                </li>
                {% else %}
                <li class="nav-item"><a class="nav-link" href="{% url 'users:register' %}">Register</a></li>
                <li class="nav-item"><a class="nav-link" href="{% url 'users:login' %}">Login</a></li>
                {% endif %}
                <div class="navbar-text">
                  <a href="#" class="search-btn">
                    <span style="color: Gold;">
                      <i class="fa fa-search fa-lg"></i>
                    </span>
                  </a>
                </div>
              </ul>
            </div>
          </div>
        </nav>
        {% if messages %}
          {% for message in messages %}
            <div class="alert alert-{{ message.tags }}">
              <div class="text-center">
                {{ message }}
              </div>
            </div>
          {% endfor %}
        {% endif %}
        {% block content %}
        {%  endblock %}

        <!-- Page Footer-->
        <footer class="main-footer">
          <div class="container">
            <div class="row">
              <div class="col-md-4">
                <div class="logo">
                  <h3 style="font-family:Mountains of Christmas">Whiskey Chirstmas</h3>
                </div>
                <div class="contact-details">
                  <p>Email: <a href="mailto:info@company.com">sjscretchen@gmail.com</a></p>
                  <ul class="social-menu">
                    <li class="list-inline-item"><a href="#"><i class="fa fa-facebook fa-2x"></i></a></li>
                    <li class="list-inline-item"><a href="#"><i class="fa fa-twitter fa-2x"></i></a></li>
                    <li class="list-inline-item"><a href="#"><i class="fa fa-instagram fa-2x"></i></a></li>
                    <li class="list-inline-item"><a href="#"><i class="fa fa-reddit fa-2x"></i></a></li>
                  </ul>
                </div>
              </div>
              <div class="col-md-4">
                <div class="menus d-flex">
                  <ul class="list-unstyled">
                    <li> <a href="{% url 'users:myprofile' %}">My Profile</a></li>
                  </ul>
                  <ul class="list-unstyled">
                    <li> <a href="{% url 'create_post' %}">Add Post</a></li>
                  </ul>
                </div>
              </div>
              <div class="col-md-4">
                <h6>Featured Members</h6>
                <div class="latest-posts">
                  <a href="#">
                    <div class="post d-flex align-items-center">

                  </div>
                </a>
              </div>
            </div>
          </div>
        </div>
        <div class="copyrights">
          <div class="container">
            <div class="row">
              <div class="col-md-6">
                <p>&copy; 2020. All rights reserved. Whiskey Chirstmas.</p>
              </div>
              <div class="col-md-6 text-right">
                <p>Template By <a href="https://bootstrapious.com/p/bootstrap-carousel" class="text-white">Bootstrapious</a>
                  <!-- Please do not remove the backlink to Bootstrap Temple unless you purchase an attribution-free license @ Bootstrap Temple or support us at http://bootstrapious.com/donate. It is part of the license conditions. Thanks for understanding :)                         -->
                </p>
              </div>
            </div>
          </div>
        </div>
      </footer>

        <!-- JavaScript files-->
        <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
        <script src="{% static 'vendor/popper.js/umd/popper.min.js' %}"> </script>
        <script src="{% static 'vendor/bootstrap/js/bootstrap.min.js' %}"></script>
        <script src="{% static 'vendor/jquery.cookie/jquery.cookie.js' %}"> </script>
        <script src="{% static 'vendor/@fancyapps/fancybox/jquery.fancybox.min.js' %}"></script>
        <script src="{% static 'js/front.js' %}"></script>

      </body>
      </html>

templates/messages.html
{% if messages %}

    {% for message in messages %}
    <!-- <div class="alert alert-light alert-dismissible">
      <button type="button" class="close" data-dismiss='alert' aria-hidden='true'>&times;</button>
        {{ message }}
    </div> -->
    <div class="alert alert-primary" role="alert">
      <button type="button" class="close" data-dismiss='alert' aria-hidden='true'>&times;</button>
      <h4 class="text-center">{{ message }}</h4>
    </div>
    {% endfor %}

{% endif %}

templates/right_side.html
{% load static %}
{% load custom_tags %}

<aside class="col-lg-4">
  <!-- Widget [Search Bar Widget]-->
  <div class="widget search">
    <header>
      <h3 class="h6">Search the blog</h3>
    </header>
    <form action="{% url 'search' %}" method="get" class="search-form">
      <div class="form-group">
        <input type="text" name="q" placeholder="What are you looking for?">
        <button type="submit" class="submit">
          <span style="color: ForestGreen;">
            <i class="fa fa-search fa-lg"></i>
          </span>
        </button>
      </div>
    </form>
  </div>
  <!-- Widget [Latest Posts Widget]        -->
  <div class="widget latest-posts">
    <header>
      <h3 class="h6">Popular Posts</h3>
    </header>
    <div class="blog-posts">
      {% hit_posts as posts  %}
      {% for post in posts %}
      <a href="{% url 'detail' post.pk post.slug %}">
        <div class="item d-flex align-items-center">
          <div class="image"><img src="{{ post.image.url }}" alt="..." class="img-fluid">
          </div>
          <div class="title"><strong>{{ post.title }}</strong>
            <div class="d-flex align-items-center">
              <div class="views"><i class="icon-eye"></i>{{ post.hit }} hits</div>
              <div class="views"> by: {{ post.user }}</div>
            </div>
          </div>
        </div>
      </a>
      {% endfor %}
      </div>
  </div>
  <!-- Widget [Categories Widget]-->
  <div class="widget categories">
    <header>
      <h3 class="h6">Categories</h3>
    </header>

    {% categories as categories %}
    {% for category in categories %}
    <div class="item d-flex justify-content-between">
      <a href="{% url 'category_detail' pk=category.id slug=category.slug %}">{{ category.title }}</a>
      <div class="text-right">
        {{ category.post_count }}
      </div>
    </div>
    {% endfor %}
    <br>
    <div class="text-center">
      <!-- Modal Button trigger  -->
      <button type="button" class="btn btn-outline-success" data-toggle="modal" data-target="#exampleModalLong"><i class="fa fa-info-circle fa-lg"></i>
      </button>
      <!-- Modal -->
      <div class="modal fade" id="exampleModalLong" tabindex="-1" role="dialog" aria-labelledby="exampleModalLongTitle" aria-hidden="true">
        <div class="modal-dialog" role="document">
          <div class="modal-content">
            <div class="modal-header">
              <h4 class="modal-title" id="exampleModalLongTitle">Dont See A Category?</h4>
              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
            <div class="modal-body">
              <p>We strive to provide accurate and real time data as this industry evolves every day. Send us a message in the contact form and we will discuss adding your Category to the site!</p>
            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-success" data-dismiss="modal">Back to Site</button>
            </div>
          </div>
        </div>
      </div>
    </div>


  </div>
  <!-- Widget [Tags Cloud Widget]-->
  <div class="widget tags">
    <header>
      <h3 class="h6">Tags</h3>
    </header>
    <ul class="list">
      {% tags as labels %}
      {% for label in labels %}
      <div class="item d-flex justify-content-center">
        <li class="list-inline-item"><a href="{% url 'tag_detail' label.slug %}" class="tag">
          <i class="fa fa-tags"></i> {{ label }} ~ {{ label.post_count}}</a>
        </li>
      </div>
      {% endfor %}
    </ul>
  </div>
</aside>