posts/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path('', IndexView.as_view(), name="index"),
    path('detail/<int:pk>/<slug:slug>', PostDetail.as_view(), name="detail"),
    path('category/<int:pk>/<slug:slug>', CategoryDetail.as_view(), name="category_detail"),
    path('tag/<slug:slug>', TagDetail.as_view(), name="tag_detail"),
    path('create-post', CreatePostView.as_view(), name="create_post"),
    path('update-post/<int:pk>/<slug:slug>', UpdatePostView.as_view(), name="update_post"),
    path('delete-post/<int:pk>/<slug:slug>', DeletePostView.as_view(), name="delete_post"),
    path('search/', search, name="search"),
    path('newsletter/', HomeView.as_view(), name="newsletter"),
    # All posts page
    path('blog/', blog, name='post-list'),
]

users/urls.py
from django.urls import path
from . views import *
from django.contrib.auth import views as authViews

app_name = 'users'
urlpatterns = [
    path('', UserListView.as_view(), name='user_list'),
    path('register/', RegisterView.as_view(), name='register'),
    path('login/', UserLoginView.as_view(), name='login'),
    path('logout/', UserLogoutView.as_view(), name='logout'),
    path('password-change/', authViews.PasswordChangeView.as_view(), name='password_change'),
    path('password-change-done/', authViews.PasswordChangeDoneView.as_view(), name='password_change_done'),
    path('update-profile/<slug:slug>/', UserProfileUpdateView.as_view(), name='update_profile'),
    path('myprofile/', UserProfileView.as_view(), name='myprofile'),
    path('<int:pk>/', UserPostView.as_view(), name='user_posts'),

]

whiskeyChristmas/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from posts.views import blog


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('posts.urls')),
    path('users/', include('users.urls')),
    path('tinymce/', include('tinymce.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/models.py
from django.db import models
from django.conf import settings
from django.template.defaultfilters import slugify
from django.db.models.signals import post_save
from PIL import Image

class UserProfile(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    bio = models. TextField(max_length=1000, blank=True)
    image = models.ImageField(blank=True, null=True, default='users/no_profile_pic.png', upload_to='users')
    slug = models.SlugField(editable=False)
    last_login = models.DateTimeField(null=True, blank=True)
    date_joined = models.DateTimeField(null=True, blank=True)

    def __str__(self):
        # Display username in admin panel
        return self.user.username

def create_user_profile(sender, instance, created, **kwargs):
    if created:
        UserProfile.objects.create(user=instance)

post_save.connect(create_user_profile, sender=settings.AUTH_USER_MODEL)

users/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django import forms
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Field, Submit
from users.models import UserProfile

class RegisterForm(UserCreationForm):
    username = forms.CharField(max_length=50)
    email = forms.EmailField(max_length=50)
    password1 = forms.CharField()
    password2 = forms.CharField()

    class Meta(UserCreationForm):
        model = User
        fields = ('username', 'email', 'password1', 'password2',)


class UserProfileForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(UserProfileForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_method = 'post'
        self.helper.field_class = 'mt-10'
        self.helper.layout = Layout(
            # Field('date_joined', css_class='single-input'),
            Field('bio', css_class='single-input'),
            Field('image', css_class='single-input'),

        )

        self.helper.add_input(Submit('submit', 'Update', css_class='btn btn-success'))

    class Meta:
        model = UserProfile
        fields = ('bio','image',)
        widgets = {
            # 'date_joined': forms.DateInput(attrs={'type':'date'})
        }

users/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from django.contrib.auth.views import LoginView, LogoutView
from django.views.generic import CreateView, UpdateView, ListView
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.contrib.messages.views import SuccessMessageMixin
from django.urls import reverse
from .forms import RegisterForm, UserProfileForm
from users.models import UserProfile
from posts.models import Post

class RegisterView(CreateView):
    template_name = 'users/register.html'
    form_class = RegisterForm
    success_url = '/'


class UserLoginView(LoginView):
    template_name = 'users/login.html'


class UserLogoutView(LogoutView):
    template_name = 'users/login.html'


@method_decorator(login_required(login_url='/users/login'), name='dispatch')
class UserProfileUpdateView(SuccessMessageMixin, UpdateView):
    model = UserProfile
    template_name = 'users/profile-update.html'
    form_class = UserProfileForm
    success_message = 'Your Profile has been updated!'

    def form_valid(self, form):
        form.instance.user = self.request.user
        form.save()
        return super(UserProfileUpdateView, self).form_valid(form)

    def get_success_url(self):
        return reverse('users:update_profile', kwargs={'slug':self.object.slug})

    def get(self, request, *args, **kwargs):
        self.object = self.get_object()
        if self.object.user != request.user:
            return HttpResponseRedirect('/')

        return super(UserProfileUpdateView, self).get(request, *args, **kwargs)


@method_decorator(login_required(login_url='/users/login'), name='dispatch')
class UserProfileView(ListView):
    template_name = 'users/my-profile.html'
    model = Post
    context_object_name = 'userposts'
    paginate_by = 5

    def get_context_data(self, **kwargs):
        context = super(UserProfileView, self).get_context_data(**kwargs)
        context['userprofile'] = UserProfile.objects.get(user=self.request.user)
        return context

    def get_queryset(self):
        return Post.objects.filter(user=self.request.user).order_by('-id')


class UserPostView(ListView):
    template_name = 'users/user-post.html'
    model = Post
    context_object_name = 'posts'
    paginate_by = 5

    def get_queryset(self):
        return Post.objects.filter(user=self.kwargs['pk'])


class UserListView(ListView):
    template_name = 'users/user-list.html'
    model = UserProfile
    context_object_name = 'profiles'
    paginate_by = 4

    def get_context_data(self, **kwargs):
        context = super(UserListView, self).get_context_data(**kwargs)
        return context

templates/users/login.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<div class="container">
  <br>
  {% if not user.is_authenticated %}
  <h2 style="color:forestgreen">Welcome Back <img src="{% static 'img/whiskeyChristmasLogo_full.gif' %}" alt="whiskey christmas GIF icon" style="width:auto;height:36px;"></h2><hr>
  <div>
    <p>Not a member? <a href="{% url 'users:register' %}">Signup!</a>
    </p>
  </div>
  <br>
  <form method="post">
    {% csrf_token %}

    {% if form.errors %}
    <div id="errors">
      <div class="inner">
        <p style="color:red">Please correct the errors below</p>
        <ul>
          {% for field in form %}
          {% if field.errors %}
          <li>{{ form.label }} {{ field.errors|striptags }}</li>
          {% endif %}
          {% endfor %}
        </ul>
      </div>
    </div>
    <br>
    {% endif %}

    <div class="mt-10">
      <input type="text" name="username" placeholder="username" onfocus="this.placeholder = ''" onblur="this.placeholder = 'username'" required="" class="form-control">
    </div><br>

    <div class="mt-10">
      <input type="password" name="password" placeholder="password" onfocus="this.placeholder = ''" onblur="this.placeholder = 'password'" required="" class="form-control">
    </div><br>

    <button name="submit" class="btn btn-success"><i class="fa fa-paper-plane fa-lg"></i> Login</button>
  </form>
  <br>
  {% else %}
  <br><br><br>
  <div class="text-center">
      <h2 style="font-family:Mountains of Christmas" class="display-4">You are already logged in!</h2><hr>
      <a href="{% url 'index' %}"><i class="fa fa-home fa-3x"></i></a>
  </div>
  <br><br><br>
  {% endif %}
</div>

{% endblock %}

templates/users/my-profile.html
{% extends 'base.html' %}
{% load custom_tags %}
{% load static %}

{% block content %}

<div class="container">
  <div class="row">
    <main class="posts-listing col-lg-8">
      <div class="container">
        <!-- Profile Details -->
        <div class="page-content page-container-fluid" id="page-content">
          <div class="card">
            <div class="card-body text-center">
              <div> <img src="{{ userprofile.image.url }}" class="img-lg rounded-circle mb-4" alt="profile image">
                <h4>Profile of: {{ userprofile.user.username}} <img src="{% static 'img/whiskeyChristmasLogo_green.gif' %}" alt="logo" style="width:auto;height:48px;"></h4>
                <p class="text-muted mb-0">Bio: {{ userprofile.bio|linebreaks }}</p>
              </div>

              <a href="{% url 'create_post' %}"><button class="btn btn-success">Post</button></a>
              <a href="{% url 'users:update_profile' slug=userprofile.slug %}"><button class="btn btn-warning">Update Profile</button></a>
              <br><br>
              <div class="border-top pt-3">
                <div class="row">
                  <div class="col-6">
                    <h6>Joined on</h6>
                    <p>{{ userprofile.user.date_joined }}</p>
                  </div>
                  <div class="col-6">
                    <h6>Last Login</h6>
                    <p>{{ userprofile.user.last_login }}</p>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
        <br>

        <h4 class="text-center">Your Posts</h4><br>
        <!-- Pagination -->
        {% if is_paginated %}
        <nav aria-label="Page navigation example">
          <ul class="pagination pagination-template d-flex justify-content-center">

            {% if page_obj.has_previous %}
            <li class="page-item">
              <a href="?page={{ page_obj.previous_page_number }}" class="page-link"> <i class="fa fa-angle-left fa-lg"></i></a>
            </li>
            {% else %}
            <li class="page-item disabled">
              <a href="#" class="page-link"></a>
            </li>
            {% endif %}

            {% for i in paginator.page_range %}
            {% if page_obj.number == i  %}
            <li class="page-item"><a href="#" class="page-link active">{{ i }}</a></li>
            {% else %}
            <li class="page-item"><a href="?page={{ i }}" class="page-link">{{ i }}</a></li>
            {% endif %}
            {% endfor %}

            {% if page_obj.has_next %}
            <li class="page-item"><a href="?page={{ page_obj.next_page_number }}" class="page-link"><i class="fa fa-angle-right fa-lg"></i></a></li>
            {% else %}
            <li class="page-item disabled">
              <a href="#" class="page-link"></a>
            </li>
            {% endif %}

          </ul>
          <br>
        </nav>
        {% endif %}

        <div class="row">
          {% for post in userposts %}
          <div class="post col-xl-6">
            <div class="post-thumbnail"><a href="#"><img src="{{ post.image.url }}" alt="post image" class="img-fluid"></a></div>
            <div class="post-details">
              <div class="post-meta d-flex justify-content-between">
                <div class="category">
                  {% for tag in post.tag.all %}
                  <a href="{% url 'tag_detail' tag.slug %}"><i class="fa fa-tags"></i> {{ tag.title }}</a>
                  {% endfor %}
                </div>
              </div><a href="{% url 'detail' pk=post.pk slug=post.slug %}">
                <h3 class="h4">{{ post.title }}</h3></a>
                <p class="text-muted">{{ post.title|truncatechars:50 }}</p>
                <footer class="post-footer d-flex align-items-center"><a href="#" class="author d-flex align-items-center flex-wrap">
                  <div class="date"><i class="icon-clock"></i>{{ post.timestamp|timesince }} ago</div>
                </footer>
              </div>
            </div>
          {% endfor %}

          </div>
        </div>
      </main>
      <aside class="col-lg-4">

        <!-- Widget [Latest Posts Widget]        -->
        <div class="widget latest-posts">
          <header>
            <h3 class="h6">Popular Posts</h3>
          </header>
          <div class="blog-posts">
            {% hit_posts as posts  %}
            {% for post in posts %}
            <a href="{% url 'detail' post.pk post.slug %}">
              <div class="item d-flex align-items-center">
                <div class="image"><img src="{{ post.image.url }}" alt="..." class="img-fluid">
                </div>
                <div class="title"><strong>{{ post.title }}</strong>
                  <div class="d-flex align-items-center">
                    <div class="views"><i class="icon-eye"></i>{{ post.hit }} hits</div>
                    <div class="views"> by: {{ post.user }}</div>
                  </div>
                </div>
              </div>
            </a>
            {% endfor %}
            </div>
        </div>
        <!-- Widget [Categories Widget]-->
        <div class="widget categories">
          <header>
            <h3 class="h6">Categories</h3>
          </header>

          {% categories as categories %}
          {% for category in categories %}
          <div class="item d-flex justify-content-between">
            <a href="{% url 'category_detail' pk=category.id slug=category.slug %}">{{ category.title }}</a>
            <div class="text-right">
              {{ category.post_count }}
            </div>
          </div>
          {% endfor %}
          <br>
          <div class="text-center">
            <!-- Modal Button trigger  -->
            <button type="button" class="btn btn-outline-success" data-toggle="modal" data-target="#exampleModalLong"><i class="fa fa-info-circle fa-lg"></i>
            </button>
            <!-- Modal -->
            <div class="modal fade" id="exampleModalLong" tabindex="-1" role="dialog" aria-labelledby="exampleModalLongTitle" aria-hidden="true">
              <div class="modal-dialog" role="document">
                <div class="modal-content">
                  <div class="modal-header">
                    <h4 class="modal-title" id="exampleModalLongTitle">Dont See A Category?</h4>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                      <span aria-hidden="true">&times;</span>
                    </button>
                  </div>
                  <div class="modal-body">
                    <p>We strive to provide accurate and real time data as this industry evolves every day. Send us a message in the contact form and we will discuss adding your Category to the site!</p>
                  </div>
                  <div class="modal-footer">
                    <button type="button" class="btn btn-success" data-dismiss="modal">Back to Site</button>
                  </div>
                </div>
              </div>
            </div>
          </div>


        </div>
        <!-- Widget [Tags Cloud Widget]-->
        <div class="widget tags">
          <header>
            <h3 class="h6">Tags</h3>
          </header>
          <ul class="list">
            {% tags as labels %}
            {% for label in labels %}
            <li class="list-inline-item"><a href="{% url 'tag_detail' label.slug %}" class="tag"><i class="fa fa-tags"></i> {{ label }} ~ {{ label.post_count}}</a></li>
            {% endfor %}
          </ul>
        </div>
      </aside>

    </div>
  </div>

  {% endblock content %}

templates/users/profile-update.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block content %}

<div class="container">
  <br>
  <h2 style="color:forestgreen">Update Profile <img src="{% static 'img/whiskeyChristmasLogo_full.gif' %}" alt="whiskey christmas GIF icon" style="width:auto;height:36px;"></h2><hr>
  {% crispy form %}
  <br>

</div>

{% endblock %}

templates/users/register.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<section class="blog_area p_120">
  <div class="container">
    <div class="row">
      <div class="container-fluid">
        <div class="blog_left_sidebar">

          <h2 style="color:forestgreen">Register <img src="{% static 'img/whiskeyChristmasLogo_full.gif' %}" alt="whiskey christmas GIF icon" style="width:auto;height:36px;"></h2><hr>
          <div>
            <p>Already a member? <a href="{% url 'users:login' %}">Login</a>
            </p>
          </div>
          <br>
          <form method="post">
            {% csrf_token %}

            {% if form.errors %}
            <div id="errors">
              <div class="inner">
                <p style="color:red">Please correct the errors below</p>
                <ul>
                  {% for field in form %}
                  {% if field.errors %}
                  <li>{{ form.label }} {{ field.errors|striptags }}</li>
                  {% endif %}
                  {% endfor %}
                </ul>
              </div>
            </div>
            <br>
            {% endif %}

            <div class="mt-10">
							<input type="text" name="username" placeholder="username" onfocus="this.placeholder = ''" onblur="this.placeholder = 'username'" required="" class="form-control">
						</div><br>
            <div class="mt-10">
							<input type="text" name="email" placeholder="email" onfocus="this.placeholder = ''" onblur="this.placeholder = 'email'" required="" class="form-control">
						</div><br>
            <div class="mt-10">
							<input type="password" name="password1" placeholder="password" onfocus="this.placeholder = ''" onblur="this.placeholder = 'password'" required="" class="form-control">
						</div><br>

            <br>
            <h5>Password rules:</h5>
            <ul class="list-group list-group-flush">
              <li class="list-group-item"><i class="fa fa-info-circle"></i>  Can't be too similar to your other personal information.</li>
              <li class="list-group-item"><i class="fa fa-info-circle"></i>  Must contain at least 8 characters.</li>
              <li class="list-group-item"><i class="fa fa-info-circle"></i>  Can’t be a commonly used password.</li>
              <li class="list-group-item"><i class="fa fa-info-circle"></i>  Can’t be entirely numeric.</li>
            </ul>
            <br>

            <div class="mt-10">
							<input type="password" name="password2" placeholder="re-type password" onfocus="this.placeholder = ''" onblur="this.placeholder = 're-type password'" required="" class="form-control">
						</div>
            <br>
            <button name="submit" class="btn btn-success"><i class="fa fa-paper-plane fa-lg"></i> Register</button>
          </form>
        </div>
      </div>
    </div>
  </div>
</section>

{% endblock %}

templates/users/user-list.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<div class="container">


  <div class="row">
    <main class="posts-listing col-lg-8">
      <h2 class="text-center">All Members<img src="{% static 'img/whiskeyChristmasLogo_green.gif' %}" alt="logo" style="width:auto;height:48px;"></h2>

      <!-- Pagination -->
      {% if is_paginated %}
      <nav aria-label="Page navigation example">
        <ul class="pagination pagination-template d-flex justify-content-center">

          {% if page_obj.has_previous %}
          <li class="page-item">
            <a href="?page={{ page_obj.previous_page_number }}" class="page-link"> <i class="fa fa-angle-left fa-lg"></i></a>
          </li>
          {% else %}
          <li class="page-item disabled">
            <a href="#" class="page-link"></a>
          </li>
          {% endif %}

          {% for i in paginator.page_range %}
          {% if page_obj.number == i  %}
          <li class="page-item"><a href="#" class="page-link active">{{ i }}</a></li>
          {% else %}
          <li class="page-item"><a href="?page={{ i }}" class="page-link">{{ i }}</a></li>
          {% endif %}
          {% endfor %}

          {% if page_obj.has_next %}
          <li class="page-item"><a href="?page={{ page_obj.next_page_number }}" class="page-link"><i class="fa fa-angle-right fa-lg"></i></a></li>
          {% else %}
          <li class="page-item disabled">
            <a href="#" class="page-link"></a>
          </li>
          {% endif %}

        </ul>
        <br>
      </nav>
      {% endif %}

      <div class="container">
        {% for profile in profiles %}
        <!-- Profile Details -->
        <div class="page-content page-container-fluid" id="page-content">
          <div class="card">
            <div class="card-body text-center">
              <div> <img src="{{ profile.image.url }}" class="img-lg rounded-circle mb-4" alt="profile image">
                <h4>Profile of: {{ profile.user.username}} <img src="{% static 'img/whiskeyChristmasLogo_green.gif' %}" alt="logo" style="width:auto;height:48px;"></h4>
                {% if profile.bio %}
                <p class="text-muted mb-0">Bio: {{ profile.bio|linebreaks }}</p>
                {% else %}
                <p class="text-muted mb-0">No Bio</p><br>
                {% endif %}
              </div>

              <a href="{% url 'users:user_posts' pk=profile.user.pk %}"><button class="btn btn-outline-success">View Users Posts</button></a>
              <br><br>
              <div class="border-top pt-3">
                <div class="row">
                  <div class="col-6">
                    <h6>Joined on</h6>
                    <p>{{ profile.user.date_joined }}</p>
                  </div>
                  <div class="col-6">
                    <h6>Last Login</h6>
                    <p>{{ profile.user.last_login }}</p>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
        <br>
        {% endfor %}

      </div>
    </main>

    {% include 'right_side.html' %}

  </div>
</div>

{% endblock content %}

templates/users/user-post.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<div class="container">


  <div class="row">
    <!-- Latest Posts -->
    <main class="posts-listing col-lg-8">
      <div class="container">
        <h2 class="text-center">Users Posts <img src="{% static 'img/whiskeyChristmasLogo_green.gif' %}" alt="logo" style="width:auto;height:48px;"></h2><hr>

        <!-- Pagination -->
        {% if is_paginated %}
        <nav aria-label="Page navigation example">
          <ul class="pagination pagination-template d-flex justify-content-center">

            {% if page_obj.has_previous %}
            <li class="page-item">
              <a href="?page={{ page_obj.previous_page_number }}" class="page-link"> <i class="fa fa-angle-left fa-lg"></i></a>
            </li>
            {% else %}
            <li class="page-item disabled">
              <a href="#" class="page-link"></a>
            </li>
            {% endif %}

            {% for i in paginator.page_range %}
            {% if page_obj.number == i  %}
            <li class="page-item"><a href="#" class="page-link active">{{ i }}</a></li>
            {% else %}
            <li class="page-item"><a href="?page={{ i }}" class="page-link">{{ i }}</a></li>
            {% endif %}
            {% endfor %}

            {% if page_obj.has_next %}
            <li class="page-item"><a href="?page={{ page_obj.next_page_number }}" class="page-link"><i class="fa fa-angle-right fa-lg"></i></a></li>
            {% else %}
            <li class="page-item disabled">
              <a href="#" class="page-link"></a>
            </li>
            {% endif %}

          </ul>
          <br>
        </nav>
        {% endif %}

        <div class="row">

          {% for post in posts %}
          <div class="post col-xl-6">
            <div class="post-thumbnail"><a href="#"><img src="{{ post.image.url }}" alt="post image" class="img-fluid"></a></div>
            <div class="post-details">
              <div class="post-meta d-flex justify-content-between">
                <div class="category">
                  {% for tag in post.tag.all %}
                  <a href="{% url 'tag_detail' tag.slug %}"><i class="fa fa-tags"></i> {{ tag.title }}</a>
                  {% endfor %}
                </div>
              </div><a href="{% url 'detail' pk=post.pk slug=post.slug %}">
                <h3 class="h4">{{ post.title }}</h3></a>
                <p class="text-muted">{{ post.title|truncatechars:50 }}</p>
                <footer class="post-footer d-flex align-items-center"><a href="#" class="author d-flex align-items-center flex-wrap">
                  <div class="title"><span>by: {{ post.user }}</span></div></a>
                  <div class="date"><i class="icon-clock"></i>{{ post.timestamp|timesince }} ago</div>
                </footer>
            </div>
          </div>
          {% endfor %}

          </div>
        </div>
      </main>

      {% include 'right_side.html' %}

    </div>
  </div>

  {% endblock content %}